# Generated by Django 4.1 on 2022-08-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_tgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tgid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
